version: '3.8'

services:
  app:
    build: 
      context: .
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp_modular
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_password
    volumes:
      - mysql_dev_data:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  # Laravel Telescope - Development Debugging
  telescope:
    build: 
      context: .
      target: backend
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    command: php artisan telescope:install

  # Node.js for Frontend Development
  node:
    image: node:20-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_dev_data:
