version: '3.8'

services:
  # PHP Application with Octane
  app:
    build: 
      context: .
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    command: php artisan octane:start --host=0.0.0.0 --port=8000 --workers=4
    restart: unless-stopped

  # MySQL 8.4 - Latest & Optimized
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-erp_modular}
      MYSQL_USER: ${DB_USERNAME:-erp_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-erp_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  # Redis 7.2 - Latest
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped

  # Nginx - High Performance
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

  # Laravel Horizon - Queue Management
  horizon:
    build: 
      context: .
      target: backend
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
    depends_on:
      - mysql
      - redis
    command: php artisan horizon
    restart: unless-stopped

  # ClickHouse - Analytics (Optional)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  clickhouse_data:
